version: '3.8'

services:
  app:
    build: .  # 从当前目录构建 Docker 镜像
    image: background-image-api:latest
    container_name: backgroundImageApi
    ports:
      - "3000:3000"  # 将容器的 3000 端口映射到主机的 3000 端口
    restart: always 
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
      - ./api_call_counts.json:/app/api_call_counts.json
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
